---
name: kos-language-server
description: Language Server for Kerboscript from the kOS Kerbal Space Program mod.
homepage: https://github.com/jonnyboyC/kos-language-server
licenses:
  - MIT
languages:
  - Kerboscript
categories:
  - LSP
  - Linter
  - Formatter

source:
  id: pkg:npm/kos-language-server@1.1.5

schemas:
  lsp: vscode:https://raw.githubusercontent.com/jonnyboyC/kos-language-server/5319c84b67a195629019c555f870bbff3920f5eb/package.json

bin:
  kls: npm:kls
